# Generated by Django 4.2.6 on 2023-10-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashed_mobile_number',
            field=models.CharField(default=123, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
