# Generated by Django 4.2.6 on 2023-10-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_botmodel_file_alter_botmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
